project: h8324

targets:
  - SailfishOS-4.0.1.48-aarch64

rpms: RPMS

buildoptions: -j6

macros:
  - sailfishos 4.0
  - sailfish_build 1

install:
  - bluez5
  - droid-hal-apollo-kernel-modules
  - cpio
  - libhybris-libGLESv2
  - libhybris-libwayland-egl
  - libhybris-libEGL
  - droid-config-h8324
  - automake
  - libtool
