project: tama

targets:
  - SailfishOS-4.1.0.23-aarch64

rpms: RPMS

options:
  - allow-vendor-change

buildoptions: -j6

macros:
  - vendor meego
  - sailfishos 4.0

install:
  - droid-hal-apollo-devel
  - libhybris-libGLESv2 libhybris-libwayland-egl libhybris-libEGL
  - bluez5

skip_rpms:
  - patterns-sailfish-device-configuration
  - droid-hal-version
  - .*-bluez4-
  - .*-kickstart-configuration-
  - droid-hal-akari-devel
  - droid-hal-akatsuki-devel
