project: tama

targets:
  - SailfishOS-4.0.1.48-aarch64

rpms: RPMS

options:
  - allow-vendor-change

buildoptions: -j6

macros:
  - vendor meego
  - sailfishos 4.0

install:
  - droid-hal-apollo-devel
  - libhybris-libGLESv2 libhybris-libwayland-egl libhybris-libEGL
  - bluez5
