project: tama

targets:
  - SailfishOS-4.0.1.48-aarch64

rpms: RPMS

buildoptions: -j6

macros:
  - sailfishos 4.0

install:
  - droid-hal-apollo-devel
  - droid-hal-akari-kernel-modules
  - droid-hal-apollo-kernel-modules
  - libhybris-libGLESv2
  - libhybris-libwayland-egl
  - libhybris-libEGL
  - bluez5
